--changeset author:chuckpilon id:populate-players
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Tim', 'Abbs', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Kyle', 'Anderson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Douglas', 'Becker', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Whitey', 'Belz', 'whiteyp@yahoo.com', '‭+1 (651) 829-0921');
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Dave', 'Bennett', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Cameron', 'Boyd', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Bruce', 'Brunner', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Roger', 'Burgwald', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('John', 'Chaney', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Rick', 'Cheeseman', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Mark', 'Cotton', 'cotton6@comcast.net', '‭+1 (651) 324-8812‬');
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Bryce', 'Cruey', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Tim', 'Culbertson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Erik', 'Erdell', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Erik', 'Ganeles', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Dan', 'Goettl', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Aleksey', 'Gonikman', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Anatoliy', 'Gonikman', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Johannes', 'Grosen', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Jerry', 'Hanson', NULL, '+‭1 (612) 220-8714');
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Swede', 'Hanson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Joe', 'Hart', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Rian', 'Heaslip', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Adam', 'Hendrickson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Aaron', 'Hushagen', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Andy', 'Huttner', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Mike', 'Isabella', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Tim', 'Jarvis', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Don', 'Kessler', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Jerry', 'Knutson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Tyler', 'Knutson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Everett', 'Larson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Brad', 'Lein', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Brian', 'Lunseth', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('John', 'Lutz', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Mike', 'Lutz', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Ron', 'Lutz', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Tom', 'Lutz', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Joe', 'Marrs', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Mitch', 'Martin', 'mitch24@gmail.com', '‭+1 (612) 810-7813‬');
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Casey', 'Mereness', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Jim', 'Morgan', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Mike', 'Motzko', NULL, '+‭1 (651) 491-2908');
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Troy', 'Pfeifer', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Chuck', 'Pilon', 'chuck.pilon@gmail.com', '+1 (651) 246-9625');
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Brad', 'Raymer', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Corey', 'Risty', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Dean', 'Running', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Dave', 'Schmaltz', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Dmitry', 'Sonkin', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Greg', 'Strantz', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Carter', 'Swenson', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Matt', 'Trok', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Kurt', 'Trushenski', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Roger', 'Walsh', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('David', 'Weinard', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Seth', 'Weisinger', NULL, NULL);
INSERT INTO players (first_name, last_name, email, mobile_phone) VALUES ('Chad', 'Zabel', NULL, NULL);
